### ISSUE TITLE
CloudFlare API change has broken whitelister

### ISSUE THREAD

**Issue by kjacobsen** [DonnchaC/cloudflare-tor-whitelister#4]
Hi,
Just went to run the script and recieved the following errors:

2015-07-11 21:54:55,280 [INFO]: Successfully authenticated to the CloudFlare API
2015-07-11 21:54:55,281 [INFO]: No zone specified. Whitelist will be applied across all domains.
Traceback (most recent call last):
  File "cloudflare-whitelist.py", line 346, in <module>
    main()
  File "cloudflare-whitelist.py", line 235, in main
    rules = fetch_access_rules(session, 1, zone_id=zone_id)
  File "cloudflare-whitelist.py", line 70, in fetch_access_rules
    raise CloudFlareAPIError(res['errors'])
**main**.CloudFlareAPIError: [{'code': 7003, 'message': 'Could not route to /user/firewall/packages/access_rules/rules, perhaps your object identifier is invalid?'}, {'code': 7000, 'message': 'No route for that URI'}]

Further investigation seems to point to the firewall packages being removed from the API. I can't see in the documentation any mention of /firewall/packages/access_rules any more.

I poked around with some code of my own and it seems that CloudFlare have indeed moved some things around.

**Comment by kjacobsen** [comment]
i have raised a support case with CloudFlare. Will let you know the response.

**Comment by DonnchaC** [comment]
Great, thanks for reporting this. I'll try push out a fix tomorrow Sunday, or Monday.

**Comment by kjacobsen** [comment]
Might be worth looking at the older Client API, however from the quick testing I ran, I am not sure it supports IPv6 addresses.

**Comment by benjojo** [comment]
@kjacobsen You are right, that API does not unfortunately support v6 addresses.

**Comment by DonnchaC** [comment]
Thanks for the responses on this ticket. I've updated the endpoints in the code to match the moved CloudFlare access rule endpoints. This tool is currently using undocumented endpoints to manage the access rules, so unfortunately this may break again in future if CloudFlare makes breaking changes to the API.

**Comment by kjacobsen** [comment]
Hey, how did you find the new endpoints? I can't see them in the documentation from CloudFlare.

**Comment by DonnchaC** [comment]
Hi, the v4 API access rule endpoints aren't publicly documented. I was able to determine the endpoints by analysing the v4 endpoints used by the CloudFlare web UI.
