### ISSUE TITLE
README: add link to alternative "how to whitelist Tor visitors via Cloudflare Dashboard"

### ISSUE THREAD

**Issue by lidel** [DonnchaC/cloudflare-tor-whitelister#6]
It is possible to whitelist Tor (`T1`) visitors via the updated dashboard:
- https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

I think adding short node in the README may improve discoverability.

**Comment by DonnchaC** [comment]
@lidel Thanks very much for the reminder. I've updated the README now.
